name: mvvm_builder
description: A widget builder to use MVVM design pattern. Force Split code of view / component and help you manage component refresh state.
version: 3.0.1-null.safety
homepage: https://apparence.io
repository: https://github.com/g-apparence/flutter_mvvm

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

